### PR TITLE
feat: upgrade reactflow to @xyzflow/react

### PR DESCRIPTION
**Pull request by AndrasEszes**

### CODE REVIEW

**Comment by AndrasEszes** [comment]
There are some performance issues, so I moved it to draft.

**Comment by AndrasEszes** [comment]
> There are some performance issues, so I moved it to draft.

Performance issues are resolved now, so it's ready to review.

**Comment by gaborszakacs** [comment]
Add workflows doesn't work on an empty pipeline (new nodes are not showing, the YML changes though).

**Comment by gaborszakacs** [comment]
Not sure if it's new, new workflows are added in a somewhat random height.

image

**Review by zoltanszabo-bitrise — DISMISSED** [review]

**Review by zoltanszabo-bitrise — APPROVED** [review]

**Pull request merged**
